version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"
  target-branch: dependabot-pr
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "13:30"
    timezone: UTC
  target-branch: dependabot-pr
  ignore:
    - dependency-name: hier-config
      versions:
      - "3.*.*"
    - dependency-name: Sphinx
      versions:
      - "7.*.*"
  groups:
    python-packages:
      patterns:
        - "*"
