---
engines:
  duplication:
    enabled: true
    config:
      languages:
        - "python"
  bandit:
    enabled: true
  fixme:
    enabled: true
  radon:
    enabled: true
  coverage:
    enabled: true
    excluded_paths:
      - "tests/**"
exclude_paths:
  - ".flake8"
  - '**.md'
  - '**.rst'
  - '**.pdf'
  - '**.jpg'
  - '**.png'
  - '**.gif'
